### ISSUE TITLE
should not install java if it is already installed

### ISSUE THREAD

**Issue by yogeshVU** [sperka/ansible-role-archiva#3]
should not install jdk if it is already installed.
Current setup installs jdk even if it is already installed.

**Comment by sperka** [comment]
"jdk" is a dependency (gantsign.java) that is defined in meta/main.yml
see http://docs.ansible.com/ansible/playbooks_roles.html#role-dependencies

allow_duplicates is not set, so in case there's any issue report it on "gantsign.java" github
